[book]
title        = "vkb"
authors      = ["Pierre Marijon"]
description  = "Variant Knowledge Base"
language     = "en"
multilingual = false
src          = "website"

[build]
build-dir      = "public"
create-missing = false

[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/GenomeCAD/vkb/"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/GenomeCAD/vkb/edit/main/docs/{path}"
site-url = "https://vkb.github.io/vkb"